// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:58c0111a-21b4-420c-9270-f02df0ecf54f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BHHbU0NFv",
    "aws_user_pools_web_client_id": "2ljp01makkvhjt928q03nktduc",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "RESTAPI",
            "endpoint": "https://iktcbkitb1.execute-api.us-east-2.amazonaws.com/backend",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
